### ISSUE TITLE
revert & merge 관련 사항

### ISSUE THREAD

**Issue by rlajiun** [hotSix-square/sky-town#3]
@Semy-sudo님 스프링 워크스페이스가 HappyhouseAPI로 잡혀있는 것 같습니다.
그래서 .metadata 폴더가 생성돼서 #1 풀리퀘스트때 해당 폴더들이 다 리퀘 들어와서 예인님께서 머지했던거 일단 되돌려놨습니다.
워크스페이스를 sky-town 밖에서 잡는거로 변경 부탁드립니다!
추가로 기능 구현하실때 기능으로 네이밍해서 브랜치 나눠서 관련 기능 구현하신 후 풀리퀘스트 넣으면 좋을 것 같습니다!
혹시 또 관련 이슈 발생할까봐 병합하는거 막아놓겠습니다!
![image](https://user-images.githubusercontent.com/54028476/144881510-7eb4fd72-ddff-4c06-aca8-7ba18b958717.png)
![image](https://user-images.githubusercontent.com/54028476/144881575-6d29f427-8f05-4e67-bf8e-2621a584175d.png)

**Comment by Semy-sudo** [comment]
폴더 경로 제대로 잡는거(.metadata 안추가되게), 브랜치로 네이밍해서 기능개발 2가지 확인했습니다! 감사합니다.
